create extension if not exists pgcrypto;

alter table users
add column if not exists autogenerated boolean not null default false;

insert into users (email, display_name, password, admin, autogenerated)
values (
    'admin@koopify.piguy.nl',
    'Koopify Admin',
    crypt('admin123', gen_salt('bf')),
    true,
    true
)
on conflict (email) do nothing;
