// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type User struct {
	ID          int64
	Email       string
	DisplayName string
	Password    string
	Admin       bool
}
