// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type DeletionPolicy struct {
	ID                 bool
	DeletionDelayHours int32
}

type Order struct {
	ID                 int64
	UserID             int64
	Status             string
	TotalEurCents      int32
	AdyenPaymentLink   pgtype.Text
	AdyenReference     pgtype.Text
	AdyenSessionResult pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type OrderItem struct {
	ID             int64
	OrderID        int64
	ProductID      int64
	ProductName    string
	Quantity       int32
	UnitPriceCents int32
	CreatedAt      pgtype.Timestamptz
}

type Product struct {
	ID              int64
	Name            string
	Slug            string
	Description     string
	ImageUrl        pgtype.Text
	PriceEurCents   int32
	DiscountPercent pgtype.Int4
	InventoryCount  int32
	InStock         bool
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ProductCategory struct {
	ProductID  int64
	CategoryID int64
}

type User struct {
	ID                  int64
	Email               string
	DisplayName         string
	Password            string
	Admin               bool
	RequestedDeletionAt pgtype.Timestamptz
	DeletionScheduledAt pgtype.Timestamptz
}
