// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const cancelUserDeletion = `-- name: CancelUserDeletion :one
update users
set requested_deletion_at = null,
    deletion_scheduled_at = null
where id = $1
returning id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at
`

func (q *Queries) CancelUserDeletion(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, cancelUserDeletion, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (
    email, display_name, password
) values (
    $1, $2, $3
) returning id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at
`

type CreateUserParams struct {
	Email       string
	DisplayName string
	Password    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users
    where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getDeletionPolicy = `-- name: GetDeletionPolicy :one
select id, deletion_delay_hours from deletion_policy
    limit 1
`

func (q *Queries) GetDeletionPolicy(ctx context.Context) (DeletionPolicy, error) {
	row := q.db.QueryRow(ctx, getDeletionPolicy)
	var i DeletionPolicy
	err := row.Scan(&i.ID, &i.DeletionDelayHours)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at from users
    where id = $1 limit 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const getUserWithEmail = `-- name: GetUserWithEmail :one
select id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at from users
	where email = $1 limit 1
`

func (q *Queries) GetUserWithEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserWithEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at from users
    order by id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Password,
			&i.Admin,
			&i.RequestedDeletionAt,
			&i.DeletionScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestUserDeletion = `-- name: RequestUserDeletion :one
update users
set requested_deletion_at = now(),
    deletion_scheduled_at = now() + make_interval(hours => $2)
where id = $1
returning id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at
`

type RequestUserDeletionParams struct {
	ID    int64
	Hours int32
}

func (q *Queries) RequestUserDeletion(ctx context.Context, arg RequestUserDeletionParams) (User, error) {
	row := q.db.QueryRow(ctx, requestUserDeletion, arg.ID, arg.Hours)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update users
set display_name = $2,
    email = $3
where id = $1
returning id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at
`

type UpdateUserParams struct {
	ID          int64
	DisplayName string
	Email       string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}
