// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachProductCategory = `-- name: AttachProductCategory :exec
insert into product_categories (product_id, category_id)
values ($1, $2) on conflict do nothing
`

type AttachProductCategoryParams struct {
	ProductID  int64
	CategoryID int64
}

// Product Category Links
func (q *Queries) AttachProductCategory(ctx context.Context, arg AttachProductCategoryParams) error {
	_, err := q.db.Exec(ctx, attachProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const cancelUserDeletion = `-- name: CancelUserDeletion :one
update users
set requested_deletion_at = null,
    deletion_scheduled_at = null
where id = $1
returning id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at
`

func (q *Queries) CancelUserDeletion(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, cancelUserDeletion, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const countActiveProducts = `-- name: CountActiveProducts :one
select count(*) from products
where is_active = true
  and (coalesce($1, '') = '' or name ilike '%' || $1 || '%' or description ilike '%' || $1 || '%')
`

func (q *Queries) CountActiveProducts(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProducts, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveProductsByCategory = `-- name: CountActiveProductsByCategory :one
select count(*)
from products p
join product_categories pc on p.id = pc.product_id
where pc.category_id = $1
  and p.is_active = true
  and (coalesce($2, '') = '' or p.name ilike '%' || $2 || '%' or p.description ilike '%' || $2 || '%')
`

type CountActiveProductsByCategoryParams struct {
	CategoryID int64
	Column2    interface{}
}

func (q *Queries) CountActiveProductsByCategory(ctx context.Context, arg CountActiveProductsByCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProductsByCategory, arg.CategoryID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllProducts = `-- name: CountAllProducts :one
select count(*) from products
where (coalesce($1, '') = '' or name ilike '%' || $1 || '%' or description ilike '%' || $1 || '%')
`

// Admin: Count all products (including inactive) with search
func (q *Queries) CountAllProducts(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProducts, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllProductsByCategory = `-- name: CountAllProductsByCategory :one
select count(*)
from products p
join product_categories pc on p.id = pc.product_id
where pc.category_id = $1
  and (coalesce($2, '') = '' or p.name ilike '%' || $2 || '%' or p.description ilike '%' || $2 || '%')
`

type CountAllProductsByCategoryParams struct {
	CategoryID int64
	Column2    interface{}
}

// Admin: Count all products by category with search
func (q *Queries) CountAllProductsByCategory(ctx context.Context, arg CountAllProductsByCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProductsByCategory, arg.CategoryID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
insert into categories (name, slug)
values ($1, $2)
returning id, name, slug, created_at, updated_at
`

type CreateCategoryParams struct {
	Name string
	Slug string
}

// Categories
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
insert into orders (user_id, status, total_eur_cents, adyen_reference, adyen_session_result)
values ($1, $2, $3, $4, $5)
returning id, user_id, status, total_eur_cents, adyen_reference, adyen_session_result, created_at, updated_at
`

type CreateOrderParams struct {
	UserID             int64
	Status             string
	TotalEurCents      int32
	AdyenReference     pgtype.Text
	AdyenSessionResult pgtype.Text
}

// Orders
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Status,
		arg.TotalEurCents,
		arg.AdyenReference,
		arg.AdyenSessionResult,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalEurCents,
		&i.AdyenReference,
		&i.AdyenSessionResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
insert into order_items (order_id, product_id, product_name, quantity, unit_price_cents)
values ($1, $2, $3, $4, $5)
returning id, order_id, product_id, product_name, quantity, unit_price_cents, created_at
`

type CreateOrderItemParams struct {
	OrderID        int64
	ProductID      int64
	ProductName    string
	Quantity       int32
	UnitPriceCents int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.Quantity,
		arg.UnitPriceCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
insert into products (
    name, slug, description, image_url, price_eur_cents, discount_percent, inventory_count, in_stock, is_active
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) returning id, name, slug, description, image_url, price_eur_cents, discount_percent, inventory_count, in_stock, is_active, created_at, updated_at
`

type CreateProductParams struct {
	Name            string
	Slug            string
	Description     string
	ImageUrl        pgtype.Text
	PriceEurCents   int32
	DiscountPercent pgtype.Int4
	InventoryCount  int32
	InStock         bool
	IsActive        bool
}

// Products
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.PriceEurCents,
		arg.DiscountPercent,
		arg.InventoryCount,
		arg.InStock,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.PriceEurCents,
		&i.DiscountPercent,
		&i.InventoryCount,
		&i.InStock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (
    email, display_name, password
) values (
    $1, $2, $3
) returning id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at
`

type CreateUserParams struct {
	Email       string
	DisplayName string
	Password    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const decrementProductInventory = `-- name: DecrementProductInventory :one
update products set
    inventory_count = inventory_count - $2,
    in_stock = (inventory_count - $2) > 0,
    updated_at = now()
where id = $1 and inventory_count >= $2
returning id, name, slug, description, image_url, price_eur_cents, discount_percent, inventory_count, in_stock, is_active, created_at, updated_at
`

type DecrementProductInventoryParams struct {
	ID             int64
	InventoryCount int32
}

// Inventory management
func (q *Queries) DecrementProductInventory(ctx context.Context, arg DecrementProductInventoryParams) (Product, error) {
	row := q.db.QueryRow(ctx, decrementProductInventory, arg.ID, arg.InventoryCount)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.PriceEurCents,
		&i.DiscountPercent,
		&i.InventoryCount,
		&i.InStock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
delete from categories where id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
delete from products where id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users
    where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const detachProductCategory = `-- name: DetachProductCategory :exec
delete from product_categories where product_id = $1 and category_id = $2
`

type DetachProductCategoryParams struct {
	ProductID  int64
	CategoryID int64
}

func (q *Queries) DetachProductCategory(ctx context.Context, arg DetachProductCategoryParams) error {
	_, err := q.db.Exec(ctx, detachProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const getCategory = `-- name: GetCategory :one
select id, name, slug, created_at, updated_at
from categories where id = $1 limit 1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
select id, name, slug, created_at, updated_at
from categories where slug = $1 limit 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeletionPolicy = `-- name: GetDeletionPolicy :one
select id, deletion_delay_hours from deletion_policy
    limit 1
`

func (q *Queries) GetDeletionPolicy(ctx context.Context) (DeletionPolicy, error) {
	row := q.db.QueryRow(ctx, getDeletionPolicy)
	var i DeletionPolicy
	err := row.Scan(&i.ID, &i.DeletionDelayHours)
	return i, err
}

const getOrder = `-- name: GetOrder :one
select id, user_id, status, total_eur_cents, adyen_reference, adyen_session_result, created_at, updated_at
from orders where id = $1 limit 1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalEurCents,
		&i.AdyenReference,
		&i.AdyenSessionResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByUser = `-- name: GetOrderByUser :one
select id, user_id, status, total_eur_cents, adyen_reference, adyen_session_result, created_at, updated_at
from orders where id = $1 and user_id = $2 limit 1
`

type GetOrderByUserParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetOrderByUser(ctx context.Context, arg GetOrderByUserParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByUser, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalEurCents,
		&i.AdyenReference,
		&i.AdyenSessionResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItem = `-- name: GetOrderItem :one
select id, order_id, product_id, product_name, quantity, unit_price_cents, created_at
from order_items where id = $1 limit 1
`

func (q *Queries) GetOrderItem(ctx context.Context, id int64) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItem, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
select id, name, slug, description, image_url, price_eur_cents, discount_percent, inventory_count, in_stock, is_active, created_at, updated_at
from products where id = $1 limit 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.PriceEurCents,
		&i.DiscountPercent,
		&i.InventoryCount,
		&i.InStock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
select 
	id,
	name,
	slug,
	description,
	image_url,
	price_eur_cents,
	discount_percent,
	inventory_count,
	in_stock,
	is_active,
	created_at,
	updated_at
from products where slug = $1 limit 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.PriceEurCents,
		&i.DiscountPercent,
		&i.InventoryCount,
		&i.InStock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductCategories = `-- name: GetProductCategories :many
select c.id, c.name, c.slug, c.created_at, c.updated_at
from categories c
join product_categories pc on c.id = pc.category_id
where pc.product_id = $1
order by c.name
`

func (q *Queries) GetProductCategories(ctx context.Context, productID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, getProductCategories, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
select id, name, slug, description, image_url, price_eur_cents, discount_percent, inventory_count, in_stock, is_active, created_at, updated_at
from products where id = $1 limit 1 for update
`

func (q *Queries) GetProductForUpdate(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForUpdate, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.PriceEurCents,
		&i.DiscountPercent,
		&i.InventoryCount,
		&i.InStock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at from users
    where id = $1 limit 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const getUserWithEmail = `-- name: GetUserWithEmail :one
select id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at from users
	where email = $1 limit 1
`

func (q *Queries) GetUserWithEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserWithEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const listAllOrders = `-- name: ListAllOrders :many
select id, user_id, status, total_eur_cents, adyen_reference, adyen_session_result, created_at, updated_at
from orders order by created_at desc
`

// Admin: List all orders
func (q *Queries) ListAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalEurCents,
			&i.AdyenReference,
			&i.AdyenSessionResult,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProducts = `-- name: ListAllProducts :many
select
	id,
	name,
	slug,
	description,
	image_url,
	price_eur_cents,
	discount_percent,
	inventory_count,
	in_stock,
	is_active,
	created_at,
	updated_at
from products order by created_at desc
`

func (q *Queries) ListAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.PriceEurCents,
			&i.DiscountPercent,
			&i.InventoryCount,
			&i.InStock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProductsPaginated = `-- name: ListAllProductsPaginated :many
select id,
	name,
	slug,
	description,
	image_url,
	price_eur_cents,
	discount_percent,
	inventory_count,
	in_stock,
	is_active,
	created_at,
	updated_at
from products
where (coalesce($3, '') = '' or name ilike '%' || $3 || '%' or description ilike '%' || $3 || '%')
order by created_at desc
limit $1 offset $2
`

type ListAllProductsPaginatedParams struct {
	Limit   int32
	Offset  int32
	Column3 interface{}
}

// Admin: List all products (including inactive) with pagination and search
func (q *Queries) ListAllProductsPaginated(ctx context.Context, arg ListAllProductsPaginatedParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listAllProductsPaginated, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.PriceEurCents,
			&i.DiscountPercent,
			&i.InventoryCount,
			&i.InStock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProductsPaginatedByCategory = `-- name: ListAllProductsPaginatedByCategory :many
select
	p.id,
	p.name,
	p.slug,
	p.description,
	p.image_url,
	p.price_eur_cents,
	p.discount_percent,
	p.inventory_count,
	p.in_stock,
	p.is_active,
	p.created_at,
	p.updated_at
from products p
join product_categories pc on p.id = pc.product_id
where pc.category_id = $1
  and (coalesce($4, '') = '' or p.name ilike '%' || $4 || '%' or p.description ilike '%' || $4 || '%')
order by p.created_at desc
limit $2 offset $3
`

type ListAllProductsPaginatedByCategoryParams struct {
	CategoryID int64
	Limit      int32
	Offset     int32
	Column4    interface{}
}

// Admin: List all products by category with pagination and search
func (q *Queries) ListAllProductsPaginatedByCategory(ctx context.Context, arg ListAllProductsPaginatedByCategoryParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listAllProductsPaginatedByCategory,
		arg.CategoryID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.PriceEurCents,
			&i.DiscountPercent,
			&i.InventoryCount,
			&i.InStock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
select id, name, slug, created_at, updated_at
from categories order by name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
select id, order_id, product_id, product_name, quantity, unit_price_cents, created_at
from order_items where order_id = $1 order by created_at
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
select id, user_id, status, total_eur_cents, adyen_reference, adyen_session_result, created_at, updated_at
from orders where user_id = $1 order by created_at desc
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalEurCents,
			&i.AdyenReference,
			&i.AdyenSessionResult,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
select id,
	name,
	slug,
	description,
	image_url,
	price_eur_cents,
	discount_percent,
	inventory_count,
	in_stock,
	is_active,
	created_at,
	updated_at
from products where is_active = true
order by created_at desc
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.PriceEurCents,
			&i.DiscountPercent,
			&i.InventoryCount,
			&i.InStock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
select
	p.id,
	p.name,
	p.slug,
	p.description,
	p.image_url,
	p.price_eur_cents,
	p.discount_percent,
	p.inventory_count,
	p.in_stock,
	p.is_active,
	p.created_at,
	p.updated_at
from products p
join product_categories pc on p.id = pc.product_id
where pc.category_id = $1 and p.is_active = true
order by p.created_at desc
`

func (q *Queries) ListProductsByCategory(ctx context.Context, categoryID int64) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.PriceEurCents,
			&i.DiscountPercent,
			&i.InventoryCount,
			&i.InStock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPaginated = `-- name: ListProductsPaginated :many
select id,
	name,
	slug,
	description,
	image_url,
	price_eur_cents,
	discount_percent,
	inventory_count,
	in_stock,
	is_active,
	created_at,
	updated_at
from products
where is_active = true
  and (coalesce($3, '') = '' or name ilike '%' || $3 || '%' or description ilike '%' || $3 || '%')
order by created_at desc
limit $1 offset $2
`

type ListProductsPaginatedParams struct {
	Limit   int32
	Offset  int32
	Column3 interface{}
}

func (q *Queries) ListProductsPaginated(ctx context.Context, arg ListProductsPaginatedParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsPaginated, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.PriceEurCents,
			&i.DiscountPercent,
			&i.InventoryCount,
			&i.InStock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPaginatedByCategory = `-- name: ListProductsPaginatedByCategory :many
select
	p.id,
	p.name,
	p.slug,
	p.description,
	p.image_url,
	p.price_eur_cents,
	p.discount_percent,
	p.inventory_count,
	p.in_stock,
	p.is_active,
	p.created_at,
	p.updated_at
from products p
join product_categories pc on p.id = pc.product_id
where pc.category_id = $1
  and p.is_active = true
  and (coalesce($4, '') = '' or p.name ilike '%' || $4 || '%' or p.description ilike '%' || $4 || '%')
order by p.created_at desc
limit $2 offset $3
`

type ListProductsPaginatedByCategoryParams struct {
	CategoryID int64
	Limit      int32
	Offset     int32
	Column4    interface{}
}

func (q *Queries) ListProductsPaginatedByCategory(ctx context.Context, arg ListProductsPaginatedByCategoryParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsPaginatedByCategory,
		arg.CategoryID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.PriceEurCents,
			&i.DiscountPercent,
			&i.InventoryCount,
			&i.InStock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
select id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at from users
    order by id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Password,
			&i.Admin,
			&i.RequestedDeletionAt,
			&i.DeletionScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestUserDeletion = `-- name: RequestUserDeletion :one
update users
set requested_deletion_at = now(),
    deletion_scheduled_at = now() + make_interval(hours => $2)
where id = $1
returning id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at
`

type RequestUserDeletionParams struct {
	ID    int64
	Hours int32
}

func (q *Queries) RequestUserDeletion(ctx context.Context, arg RequestUserDeletionParams) (User, error) {
	row := q.db.QueryRow(ctx, requestUserDeletion, arg.ID, arg.Hours)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
update categories set
    name = $2,
    slug = $3,
    updated_at = now()
where id = $1
returning id, name, slug, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID   int64
	Name string
	Slug string
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.Slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderAdyenReference = `-- name: UpdateOrderAdyenReference :one
update orders set adyen_reference = $2, updated_at = now()
where id = $1
returning id, user_id, status, total_eur_cents, adyen_reference, adyen_session_result, created_at, updated_at
`

type UpdateOrderAdyenReferenceParams struct {
	ID             int64
	AdyenReference pgtype.Text
}

func (q *Queries) UpdateOrderAdyenReference(ctx context.Context, arg UpdateOrderAdyenReferenceParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderAdyenReference, arg.ID, arg.AdyenReference)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalEurCents,
		&i.AdyenReference,
		&i.AdyenSessionResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderAdyenSession = `-- name: UpdateOrderAdyenSession :one
update orders set adyen_reference = $2, adyen_session_result = $3, updated_at = now()
where id = $1
returning id, user_id, status, total_eur_cents, adyen_reference, adyen_session_result, created_at, updated_at
`

type UpdateOrderAdyenSessionParams struct {
	ID                 int64
	AdyenReference     pgtype.Text
	AdyenSessionResult pgtype.Text
}

func (q *Queries) UpdateOrderAdyenSession(ctx context.Context, arg UpdateOrderAdyenSessionParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderAdyenSession, arg.ID, arg.AdyenReference, arg.AdyenSessionResult)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalEurCents,
		&i.AdyenReference,
		&i.AdyenSessionResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
update orders set status = $2, updated_at = now()
where id = $1
returning id, user_id, status, total_eur_cents, adyen_reference, adyen_session_result, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalEurCents,
		&i.AdyenReference,
		&i.AdyenSessionResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
update products set
    name = $2,
    slug = $3,
    description = $4,
    image_url = $5,
    price_eur_cents = $6,
    discount_percent = $7,
    inventory_count = $8,
    in_stock = $9,
    is_active = $10,
    updated_at = now()
where id = $1
returning id, name, slug, description, image_url, price_eur_cents, discount_percent, inventory_count, in_stock, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID              int64
	Name            string
	Slug            string
	Description     string
	ImageUrl        pgtype.Text
	PriceEurCents   int32
	DiscountPercent pgtype.Int4
	InventoryCount  int32
	InStock         bool
	IsActive        bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.PriceEurCents,
		arg.DiscountPercent,
		arg.InventoryCount,
		arg.InStock,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.PriceEurCents,
		&i.DiscountPercent,
		&i.InventoryCount,
		&i.InStock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update users
set display_name = $2,
    email = $3
where id = $1
returning id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at
`

type UpdateUserParams struct {
	ID          int64
	DisplayName string
	Email       string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const updateUserAdmin = `-- name: UpdateUserAdmin :one
update users
set admin = $2
where id = $1
returning id, email, display_name, password, admin, requested_deletion_at, deletion_scheduled_at
`

type UpdateUserAdminParams struct {
	ID    int64
	Admin bool
}

func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAdmin, arg.ID, arg.Admin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
		&i.Admin,
		&i.RequestedDeletionAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}
